@base <http://kmr.nada.kth.se/shame/bookmarks/query-conceptalonebmrequirement>.
@prefix qel: <http://www.edutella.org/qel#>.
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
@prefix cv: <http://kmr.nada.kth.se/rdf/bookmark#>.
@prefix cl: <http://kmr.nada.kth.se/rdf/graphic#>.
@prefix no: <http://kmr.nada.kth.se/rdf/notions#>.


?(X,T,V,W)- qel:nodeType(X, qel:Resource),qel:s(X,rdf:type,rdf:Statement),qel:s(X,rdf:type,cv:ConceptBookmark),
	qel:s(X,rdf:type,T),qel:nodeType(T,qel:Resource),
	qel:s(X,rdf:predicate,rdf:type),
	qel:s(X,rdf:predicate,V),qel:nodeType(V,qel:Resource),
	qel:s(X,rdf:object,no:Concept),
	qel:s(X,rdf:object,W),qel:nodeType(W,qel:Resource).