@base <http://kmr.nada.kth.se/shame/bookmarks/query-contextmapbookmarkrequirement>.
@prefix qel: <http://www.edutella.org/qel#>.
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
@prefix cv: <http://kmr.nada.kth.se/rdf/bookmark#>.
@prefix cl: <http://kmr.nada.kth.se/rdf/graphic#>.

?(X,T,V,W)- qel:nodeType(X, qel:Resource),qel:s(X,rdf:type,rdf:Statement),qel:s(X,rdf:type,cv:ContextMapBookmark),
	qel:s(X,rdf:type,T),qel:nodeType(T,qel:Resource),
	qel:s(X,rdf:predicate,rdf:type),
	qel:s(X,rdf:predicate,V),qel:nodeType(V,qel:Resource),
	qel:s(X,rdf:object,cl:ContextMap),
	qel:s(X,rdf:object,W),qel:nodeType(W,qel:Resource).